spring:
  application:
    name: api_rest_operador
  datasource:
    url: jdbc:h2:mem:comprasdb;Mode=MySQL
  jpa:
    show-sql: true  #ver las consultas que se hacen
    hibernate:
      ddl-auto: create-drop #crear y eliminar DB.
    defer-datasource-initialization: true # espera a que el datasource se ejecute el archivo data
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

## Configuración de Instancia
server:
  port: 8089

## Configuración del microservicio buscador
buscador:
  url: http://localhost:8088

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/